### ISSUE TITLE
Přesměrování staré stránky ke stažení

### ISSUE THREAD

**Issue by AsciiWolf** [UbuntuCZ/ubuntu-cz#14]
Aktuálně se [starý url](https://www.ubuntu.cz/ziskejte/stahnout) přesměrovává na `/ziskat-ubuntu/stahnout-desktop/`. Myslím, že by bylo lepší jej přesměrovat na `/ziskat-ubuntu/`, kde jsou dostupné všechny edice Ubuntu, včetně odnoží.

**Comment by MikkCZ** [comment]
Proč ne. :)

**Comment by AsciiWolf** [comment]
Je ten redirect možné upravit někde na GitHubu? Nepodařilo se mi jej najít.

**Comment by MikkCZ** [comment]
Je definovaný v "hlavičce" cílové stránky. V tomto případě tedy v https://github.com/UbuntuCZ/ubuntu-cz/blob/master/_pages/ziskat-ubuntu/stahnout-desktop/index.html. Kam bys ho chtěl přendat je https://github.com/UbuntuCZ/ubuntu-cz/blob/master/_pages/ziskat-ubuntu/index.html.
