### ISSUE TITLE
Změna designu horního menu podle ubuntu.com

### ISSUE THREAD

**Issue by zubozrout** [UbuntuCZ/ubuntu-cz#17]
Ahoj,
nedávno jsem si všiml, že tlačítka menu v hlavičce stránky jsou na ubuntu.com jednolitá, zatímco na ubuntu.cz jsou oddělena světlejší a tmavší 1px širokou čarou. Když tento design vznikal, jsem skoro jistě přesvědčený, že ubuntu.com používalo podobný vzhled, což ale zjevně již není pravda.

Kdy ke změně došlo netuším, ale zajímalo by mě, jaký je tady na to kolem názor? Mělo by se to sjednotit, nebo je to ok tak, jak to je teď?

![obrazek](https://user-images.githubusercontent.com/3088349/53657131-90c18880-3c55-11e9-8b28-3ca170f31429.png)
vs.
![obrazek](https://user-images.githubusercontent.com/3088349/53657145-9a4af080-3c55-11e9-8277-9e415ca6dc4f.png)

Pokud by se to mělo měnit, mělo by stačit upravit něco málo v https://www.ubuntu.cz/design/style.css
konkrétně `header nav > ul > li > a` na řádku 472

a potom by to vypadalo nějak takto:

![obrazek](https://user-images.githubusercontent.com/3088349/53657439-6f14d100-3c56-11e9-96c3-965d067fdd5b.png)

 jo, jsem si vědom, že je to vlastně hrozná blbost :)

**Comment by MikkCZ** [comment]
Dobrá blbost. Tak dobrá, že bych ji klidně nechal chvíli záměrně nevyřešenou. Mohlo by to být velmi dobré vylepšení od potenciálního nového přispěvatele. :)

Ale zase ne zbytečně dlouho, samozřejmě.
