### ISSUE TITLE
Chybný SSL certifikát u https://ubuntu.cz

### ISSUE THREAD

**Issue by AsciiWolf** [UbuntuCZ/ubuntu-cz#22]
Zdá se, že `https://ubuntu.cz` nemá na rozdíl od `https://www.ubuntu.cz` platný SSL certifikát.

**Comment by MikkCZ** [comment]
Díky, napsal jsem GitHubu.

> Hi.
>
> I am using Github pages for a root domain (www.)ubuntu.cz and I have enabled HTTPS for it. The certificate for www.ubuntu.cz is fine. However I get an error fro ubuntu.cz (see https://observatory.mozilla.org/analyze/ubuntu.cz#tls). The same is for www.waterfox.cz vs. waterfox.cz. (https://observatory.mozilla.org/analyze/waterfox.cz#tls).
>
> Can you please advise me how to get the HTTPS correctly set up for both www and non-www root domain? The website should be available on www.domain.tld as is now.
>
> Michal

**Comment by MikkCZ** [comment]
Tak bohužel...

> Hi Michal,
>
> Thanks for reaching out about this! We don't currently support creating a certificate that covers both your root domain and your www subdomain. We only generate a certificate for the exact domain that you specify in the custom domain input box. I will add your +1 to that feature request internally though!
> 
> In the meantime you can work around this by pointing your www subdomain CNAME at username.github.io, and entering the non-www version of your domain into the input in the repository settings.
>
> Keep in mind that this redirect will only work when using a protocol-less or http:// link. If you explicitly specify https://www.example.com you will still likely encounter a certificate error.
>
> I hope that this is of help to you. Please let me know if I can be of further assistance.
>
> Thanks,
>
> Steve G.
> GitHub Support

Nic jako HSTS ani odkazy na https://ubuntu.cz (bez www) nejsou, takže jsme asi zatím v pohodě.

**Comment by MikkCZ** [comment]
Označil jsem to jako `wontfix`, protože s tím nemůžeme (a asi nebudeme) nic dělat, než doufat, že to brzy vyřeší.
