### ISSUE TITLE
Získávát všechny informace o vydáních Ubuntu skrze API

### ISSUE THREAD

**Issue by MikkCZ** [UbuntuCZ/ubuntu-cz#24]
Canonical má API se seznamem všech verzí Ubuntu, jejich názvy i kdy jim končí podpora. Ideální nahradit tím vlastní data uložená v repositáři.

> Fetch JSON from https://api.launchpad.net/devel/ubuntu/series
> 
> Then look at "Status".
> 
> Documentation:
> 
> https://launchpad.net/+apidoc/devel.html#distribution
> https://launchpad.net/+apidoc/devel.html#distro_series
> 
> An alternative is to use the "distro-info" package, but that (actually
> "distro-info-data" that it depends on) isn't usually updated straight
> away. Come to think of it, I'm not sure exactly when the series status
> is changed on Launchpad, either.
> 
> Another alternative is to watch the simplestreams data for cloud image
> downloads:
> http://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json
> 
> Note that in this API a bunch the product identifiers are arbitrary and
> you shouldn't rely on them. Instead filter for "well-known" keys, such as
> "arch", "release", "release_title" or "version". The presence of an
> entry with keys that match tells you that such a thing is available, but
> more entry types may become available in the future during the lifetime
> of a release, such as new types or encodings of images, images with
> different sorts of kernels, and so on.
> 
> HTH,
> 
> Robie

**Comment by zubozrout** [comment]
Hm, skvělé :). Něco takového jsem "hledal" roky, ale asi málo. Naneštěstí se k tomu ale teď nějakou dobu vůbec kvůli škole nedostanu :(. Ale nemělo by to být snad zase tak těžké (teda je otázka, jestli to řešit na serveru, nebo jen přes JS, pokud ten server zvládá CrossOrigin). Na druhou stranu když se to udělá na serveru, dá se to použít i jako zdroj pro aktualizaci všech odkazů ke stažení na stránce tak, jako je tomu doposud v podstatě ručně, ač z jednoho místa.

Nicméně, podíval jsem se na to zběžně a tady:
https://api.launchpad.net/devel/ubuntu/series
nevidím eof data. I když to jde dopočítat, pokud to přesně sedí na 9/12 měísíců a 2 roky. Ale tomu bych se raději vyhnul.

Tady zase chybí staré releasy (před 10.10):
http://cloud-images.ubuntu.com/releases/streams/v1/com.ubuntu.cloud:released:download.json
ale ty eol data tam jsou. Stejně tak je tohle užitečné pro update lokální databáze a nejspíše i k získání download linků.

No a nevím, jak se k tomu postavit. Parsovat dva zdroje a nějak to dávat dohromady? Možná, ale moc mě to neláká. Navíc když každý je jinak dlouhý.

A nebo na to hledím blbě a jde to líp :).

**Comment by MikkCZ** [comment]
Ahoj @zubozrout .

Udělal jsem PR, který by měl data stahovat automaticky. Každé sestavení se tím samozřejmě trošku protáhne, ale myslím, že to nevadí. Koukneš na něj prosím?
