### ISSUE TITLE
Sledovat návštěvnost webu

### ISSUE THREAD

**Issue by MikkCZ** [UbuntuCZ/ubuntu-cz#25]
Bylo by fajn znát alespoň trochu informace o návštěvnosti na webu. Šel bych do Google Analytics s tím, že budeme respektovat DNT.

- [x] Web - GA nemá
- [x] Wiki - GA nemá
- [x] Fórum - GA má
- [x] Google search console

@vojtechtrefny máš přístup k nějakému Google Analytics, které jsou použité na fóru? Abych nevytvářel zbytečně nové.

**Comment by vojtechtrefny** [comment]
Tak jsem tě snad úspěšně přidal jako admin do GA pro fórum. Mělo by ti přijít oznámení do mailu.

**Comment by MikkCZ** [comment]
Díky. Potvrzuji, že mám přístup. Přidám zbytek pod stejný "účet".

**Comment by MikkCZ** [comment]
A už to frčí...
