### ISSUE TITLE
Nefungují automatické překlady

### ISSUE THREAD

**Issue by AsciiWolf** [UbuntuCZ/ubuntu-cz#27]
Zdá se, že Google nám zablokoval automatické překlady přes API:

```
[TranslationService] Couldn't fetch translation for: "Ubuntu Server development summary &#8211; 26 November 2019" google-translator.js:140:14
    translate https://www.ubuntu.cz/design/translator/google-translator.js:140
[TranslationService] code 403 google-translator.js:146:17
[TranslationService] message The request is missing a valid API key. google-translator.js:146:17
[TranslationService] status PERMISSION_DENIED google-translator.js:146:17
false Could not fetch translations www.ubuntu.cz:444:19
[TranslationService] Couldn't fetch translation for: "Linux Mint 19.3 Beta Arrives with New Apps, ‘Fresh’ Artwork" google-translator.js:140:14
[TranslationService] code 403 google-translator.js:146:17
[TranslationService] message User Rate Limit Exceeded google-translator.js:146:17
...
```

**Comment by MikkCZ** [comment]
@zubozrout ty máš do toho asi největší vhled. Je možné, že by vypršela platnost API klíče nebo něco takového?

**Comment by zubozrout** [comment]
No jo :(, je to tak. Zjevně jsem tam měl jen roční free trial a dál je to už jedině zpoplatněné. Takže asi bude potřeba revertnout zpět na Yandex, který je sice horší, ale myslím, že tam žádná free period nebyla, ačkoliv všechno je zdarma samozřejmě omezené :(.

Mělo by teda víceméně stačit nahradit:
https://www.ubuntu.cz/design/translator/google-translator.js
za
https://www.ubuntu.cz/design/translator/yandex-translator.js

Naneštěstí tam podle jejich požadavků teď přibude "Powered by Yandex.Translate". Jenže mě nic lepšího nenapadá a nejsem si vědom, že by se nějaká svobodnější služba někde objevila.

Jako test to tady funguje: https://my.iubuntu.cz/, tak snad bude i na ubuntu.cz.

A tady je MR: https://github.com/UbuntuCZ/ubuntu-cz/pull/28
jen to prosím před mergnutím ještě někdo otestujte, protože je možné, že jsem něco udělal špatně.

**Comment by AsciiWolf** [comment]
Další možností je nechat ty texty nepřeložené. Automatické překlady měly stejně k dokonalosti poměrně daleko a často téměř vůbec neodpovídaly původnímu textu. :-)

**Comment by MikkCZ** [comment]
Už jsem to myslím zkoušel i dříve, IIRC jsme tam chvíli ten Yandex měli. Otestoval jsem to ještě jednou a funguje to. Ta čeština není ideální, ale funguje to, takže tento bug zavřu. Pokud by "kvalita" vadila, asi se můžeme uchýlit k tomu, že překlady dáme úplně pryč.
