### ISSUE TITLE
Aktualizovat LTS verzi Ubuntu na 20.04

### ISSUE THREAD

**Issue by AsciiWolf** [UbuntuCZ/ubuntu-cz#33]
Ubuntu 20.04 bylo dnes [vydáno](https://ubuntu.com/blog/ubuntu-20-04-lts-arrives). :-)

/cc @MikkCZ

**Comment by MikkCZ** [comment]
Ahoj.

Na https://wiki.ubuntu.cz/webov%C3%A9_str%C3%A1nky/ubuntucz by měl být kompletní postup a info, co je k tomu potřeba. Odkazy ke stažení by se měly aktualizovat sami podle dat od Canonicalu. Zbývají k tomu nějaké ruční změny a popisky. Bohužel se k tomu asi před víkendem už nedostanu. Ale kdybys měl čas na PR...

**Comment by AsciiWolf** [comment]
Ahoj,

dnes už se k tomu nedostanu, zítra nejspíš taky ne. :-/ Uvidím, jak mi to časově vyjde o víkendu.

P.S. Na [webové_stránky/ubuntucz](https://wiki.ubuntu.cz/webov%C3%A9_str%C3%A1nky/ubuntucz) jsem se smazal ze seznamu správců. Sám Ubuntu nepoužívám (pouze jej, spolu s Mintem, občas doporučuji ostatním lidem) a volného času mi již příliš moc nezbývá. Ze členů UbuntuCZ na GitHubu jsem se odstranil již začátkem roku. Nadále samozřejmě budu přispívat formou PR či zakládáním issues. Mimochodem, neměl by být v seznamu správců pro "WWW (hlavní web)" i Vojta Trefný? Ve správcích infrastruktury jeho jméno uvedeno je.

**Comment by MikkCZ** [comment]
Tak v datech to zda se už je, ale nějak se to nepropaguje. Podívám se na to dneska.

Měl bych ten seznam aktualizovat.

**Comment by AsciiWolf** [comment]
@MikkCZ Ještě menší chybička, píši ji zde, ať nemusím zakládat nový issue: Zdá se, že odkazy na obrázky z root.cz mají špatné číslování. Všechny obrázky ze stránek [Instalace](https://www.ubuntu.cz/ziskat-ubuntu/stahnout-desktop/instalace/) i [Desktop](https://www.ubuntu.cz/desktop/) odkazují na obrázky, které jsou v galerii na Root.cz o jednu pozici před správnými obrázky.

Správná čísla tedy jsou: Pro stránku Instalace: `#2`, `#3`; pro stránku Desktop: `#26`, `#28`, `#33`, `#34`.

**Comment by MikkCZ** [comment]
Opraveno v #36. Díky.
