### ISSUE TITLE
Přidat https pro releases.ubuntu.cz

### ISSUE THREAD

**Issue by xdub** [UbuntuCZ/ubuntu-cz#37]
Přechod na stažení iso souboru z https na http způsobuje problémy a hlásí bezpečnostní chybu. Zkoušeno na Firefoxu 75.

**Comment by MikkCZ** [comment]
releases.ubuntu.cz není pod naší správou, ale je to server CZ.NICu. Je to ten stejný server jako cz.releases.ubuntu.com, hostované na mirrors.nic.cz.

Nedávno jsem s NICem komunikoval a ohledně HTTPS se i ptali, jak to Ubuntu má, protože ho chtěli nasadit místo HTTP. Oficiální informace pro zrcadla myslím nebyly moc sdílné, takže skrze @tylnesh jsem je nějak spojil s lidmi z Ubuntu. Možná je čas se poptat, jaký je stav. Vidím, že tam už nějaký certifikát je, ale expirovaný, takže to minimálně zkoušeli.

**Comment by AsciiWolf** [comment]
Zdá se, že http://releases.ubuntu.cz má redirect na https verzi, nicméně ta má expirovaný certifikát.

**Comment by MikkCZ** [comment]
Jéje, to jsem rozbil já. https://github.com/UbuntuCZ/ubuntu-cz/commit/932f99f225098bd169bcda1c22aec2d1d662316b

**Comment by MikkCZ** [comment]
-> https://gitlab.com/UbuntuCZ/ubuntu-cz/-/issues
