### ISSUE TITLE
Přidání linku na torrent soubor

### ISSUE THREAD

**Issue by xdub** [UbuntuCZ/ubuntu-cz#38]
Bylo by možné na stránku s odkazem na stažení Ubuntu přidat i odkaz na torrent?

Představoval bych si to takto:
![Snímek z 2020-04-28 00-58-37](https://user-images.githubusercontent.com/25389128/80483540-8cc2f080-8956-11ea-8c9a-3ae5ee837261.png)

Zde je případně png s ikonou torrentu:
[torrent_icon.zip](https://github.com/UbuntuCZ/ubuntu-cz/files/4545479/torrent_icon.zip)

**Comment by MikkCZ** [comment]
Nestačil by obyčejný textový odkaz pod tlačítko? Ubuntu.com samotné má stažení přes BitTorrent docela schované, a myslím si, že cílová skupina pro tento web (uživatelé Windows) budou po třeba i nechtěném kliknutí na BitTorrentovou část tlačítka dost bezradní.

**Comment by MikkCZ** [comment]
Přidal jsem ten odkaz pod tlačítko. @xdub podívej se prosím, jestli je to tak vyhovující.

**Comment by xdub** [comment]
Jo, takhle to může být. Tamto byla jen taková představa - někde jsem to takhle už viděl a vypadalo to poměrně dobře. Jinak si nemyslím že by zrovna uživatelé Windows měli s torrentem nějaký problém.
