### ISSUE TITLE
Přesunout Ubuntu.cz na GitLab

### ISSUE THREAD

**Issue by MikkCZ** [UbuntuCZ/ubuntu-cz#44]
Ahoj.

Zkoušel jsem si dneska hrát s GitLabem, jeho CI/CD atd. a docela se mi zalíbil. Co byste řekli na to se tam s Ubuntu.cz přesunout? @AsciiWolf @zubozrout jako nejaktivnější přispěvatelé?

**Comment by zubozrout** [comment]
Za mě klidně. Nevím, jestli je v tom nějaká přidaná hodnota, ale pokud na to máš sílu, tak proč ne :).

**Comment by AsciiWolf** [comment]
Osobně sice používám primárně GitHub, ale s GitLabem nemám problém. :-)

**Comment by MikkCZ** [comment]
Přidanou hodnotu v tom vidím v tom, že je GitLab open source (fajn podporovat takové projekty) a plně nahradí i Travis CI (další uzavřená služba) i s tím hloupým cronem, kterým se to teď orchestruje z PHP hostingu.

**Comment by MikkCZ** [comment]
Hotovo.
