### ISSUE TITLE
CZ domény příchutí Ubuntu

### ISSUE THREAD

**Issue by MikkCZ** [UbuntuCZ/ubuntu-cz#6]
Všechny tři české weby příchutí (kubuntu.cz, lubuntu.cz a xubuntu.cz) mají stránky na stejných cestách URL jako Ubuntu.cz. Výjimkou jsou jen http://www.kubuntu.cz/novinky (a podstránky), http://www.lubuntu.cz/o_lubuntu a http://www.xubuntu.cz/snimky.

IMO stačí obsah uložit pro příští generace (https://github.com/UbuntuCZ/archiver/issues/1) a přesměrovat na Ubuntu.cz.
- Buď vše na titulní stránku,
- nebo na stejnou URL na Ubuntu.cz. To by se dalo snadno zařídit přes GH pages (fork https://github.com/UbuntuCZ/redirect-to-ubuntu-cz a nastavení souboru `CNAME`).
- A nebo vše na stránku příchutí zde.

**Comment by vojtechtrefny** [comment]
Ideální by asi bylo udělat pro každou distribuci nějakou stručnou podstránu, např. ubuntu.cz/kubuntu a tam přesměrovat úplně všechno z kubuntu.cz. Ale chápu, že to napřed musí někdo udělat. Takže bych se možná nebál přesměrovat úplně všechno na hlavní stránku a když se najde někdo, kdo by chtěl něco udělat, tak ten redirect upravit. (Mezi svátky bych měl mít trochu času, tak bych se klidně přihlásil. Udělat 3 stránky (k/x/lubuntu) s trochou textu a pár screenshotů bych ještě zvládnout mohl.)

**Comment by MikkCZ** [comment]
Super! Dám tě jako assignee. Až budeš dělat PR, můžeš ho dát na review třeba @zubozrout ? Ten bude mít asi nejlepší cit, jak ty stránky případně doladit, aby do zbytku webu zapadaly.

**Comment by MikkCZ** [comment]
Zatím dáme přesměrování, případný text můžeme přidat později.

**Comment by MikkCZ** [comment]
- [x] https://github.com/UbuntuCZ/kubuntu-cz-redirect
- [x] https://github.com/UbuntuCZ/lubuntu-cz-redirect
- [x] https://github.com/UbuntuCZ/xubuntu-cz-redirect
- [x] HTTPS pro GitHub Pages
