### ISSUE TITLE
Nahradit Ubuntu.cz

### ISSUE THREAD

**Issue by MikkCZ** [UbuntuCZ/ubuntu-cz#7]
Po dokončení #4 a https://github.com/UbuntuCZ/archiver/issues/1 (obojí hotovo) nemělo nic bránit nahradit Ubuntu.cz stránkou generovanou z tohoto repositáře.

Návrh postupu přesměrování Ubuntu.cz:
1. Změnit DNS pro všechny subdomény Ubuntu.cz, aby žádná nepoužívala CNAME na ubuntu.cz. Teď ho mají minimálně `sdruzeni.ubuntu.cz`, `komunita.ubuntu.cz`, `blog.ubuntu.cz`, `apc.ubuntu.cz`, `party.ubuntu.cz`, `shop.ubuntu.cz`.
1. Zajistit, že neexistuje wildcard CNAME `*.ubuntu.cz`, nebo alespoň nesměřuje na `ubuntu.cz` ani `www.ubuntu.cz`.
1. Přejmenovat tento repositář na `ubuntu-cz` a přidat do něj `CNAME` soubor s obsahem `www.ubuntu.cz`.
1. Upravit konfiguraci buildu Travis CI, aby (#12)
    1. sestavoval stránky pro základní cestu `/`
    1. výsledné sestavení obsahovalo `CNAME` soubor
1. Nastavit A/CNAME záznamy `ubuntu.cz` a `www.ubuntu.cz` na Github Pages.

Návrh postupu přesměrování iUbuntu.cz: fork https://github.com/UbuntuCZ/redirect-to-ubuntu-cz a nastavení souboru `CNAME`

**Comment by MikkCZ** [comment]
Ahoj @vojtechtrefny . Promiň, že ruším takhle před koncem roku. Myslím, že se pomalu můžeme pustit do přepnutí na nový web.

- [x] **komunita.u.cz** - Všechen obsah jsem v půlce prosince přesunul na _wiki.u.cz_, nastavil přesměrování přes DokuWiki a Google už si nových adres všiml. Mohl bys prosím pro _komunita.ubuntu.cz_ nastavit `CNAME` na `ubuntucz.github.io`? Připravil jsem přesměrování https://github.com/UbuntuCZ/komunita-ubuntu-cz-redirect, které nepotřebuje součinnost serveru.
- [x] **blog.u.cz** a ~**apc.u.cz**~ nemají vlastní DNS záznam. Můžu poprosit o nastavení jejich `A` na `217.31.202.60` a `AAAA` na `2001:1488:ffff::60`?
- [x] ~***.ubuntu.cz** - zároveň prosím o změnu wildcard `CNAME *` na `yasha.ubuntu.cz`, pokud tak není.~
- [x] ~**sdruzeni.u.cz**,~ **party.u.cz**, **shop.u.cz** - Tyhle tři subdomény nemají přímou náhradu, ale podle mě ani nemají žádnou hodnotu je dál mít. Můžu je po zazálohování smazat ze serveru?
- [x] **blog.u.cz** má jen jednoho autora. ~Poslal bys mi na něj prosím mailem nebo přes Telegram kontakt?~ Kontakt jsem našel. Domluvím se s ním, jak dál. O budoucnosti blogu by měl mít hlavní slovo on.

**Comment by MikkCZ** [comment]
DNS pro ubuntu.cz jsem nastavil. Změny budou mít vliv během víkendu a během zítřka už pojedeme čistě na novém. :)

**Comment by zubozrout** [comment]
Redirect z iubuntu.cz na ubuntu.cz snad kompletní. Trochu doufám, že jsem si nerozbil ani nic svého, ale to se uvidí časem.

**Comment by MikkCZ** [comment]
Super, funguje. Snad nebudeš časem litovat. :)

**Comment by zubozrout** [comment]
Lituji už teď :D, přišel jsem o své oblíbené pískoviště. I když na něj stejně nemám teď zase moc čas. Navíc změna je život a je to pro dobrou věc.
